apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: peerbot-tls
  namespace: peerbot
spec:
  secretName: peerbot-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - slack.peerbot.ai