-- migrate:up

-- Multi-vector embeddings — CONTRACT phase (on top of expand's chunk_index + unique index).
--
-- Promotes (event_id, embedding_model, chunk_index) to the PK so an event can hold
-- N chunk vectors per model. NULL-stamp legacy rows are dropped (unknown model,
-- already excluded from search) and regenerated by the embed backfill. The view is
-- decoupled from vectors — current_event_records is pure supersession masking;
-- all vector callers already read event_embeddings directly (expand release).
--
-- Chunking writes (N rows per event) ship in this release but are gated at runtime
-- via LOBU_EMBEDDING_CHUNKING until every pod runs this code (per-model delete).
-- Until the flag flips, behaviour stays one chunk-0 row per event.

DELETE FROM public.event_embeddings WHERE embedding_model IS NULL;

ALTER TABLE public.event_embeddings ALTER COLUMN embedding_model SET NOT NULL;

ALTER TABLE public.event_embeddings DROP CONSTRAINT event_embeddings_pkey;

ALTER TABLE public.event_embeddings
    ADD CONSTRAINT event_embeddings_pkey
    PRIMARY KEY USING INDEX event_embeddings_event_model_chunk_uniq;

-- CREATE OR REPLACE cannot remove columns from a view; drop and recreate without
-- embedding / embedding_model (no join to event_embeddings).
DROP VIEW IF EXISTS public.current_event_records;

CREATE VIEW public.current_event_records AS
 SELECT e.id,
    e.organization_id,
    e.entity_ids,
    e.origin_id,
    e.title,
    e.payload_type,
    e.payload_text,
    e.payload_data,
    e.payload_template,
    e.attachments,
    e.metadata,
    e.score,
    e.author_name,
    e.source_url,
    e.occurred_at,
    e.created_at,
    e.origin_parent_id,
    COALESCE(length(e.payload_text), 0) AS content_length,
    e.search_tsv,
    e.origin_type,
    e.connector_key,
    e.connection_id,
    e.feed_key,
    e.feed_id,
    e.run_id,
    e.semantic_type,
    e.client_id,
    e.created_by,
    e.interaction_type,
    e.interaction_status,
    e.interaction_input_schema,
    e.interaction_input,
    e.interaction_output,
    e.interaction_error,
    e.supersedes_event_id
   FROM public.events e
  WHERE (NOT (EXISTS ( SELECT 1
           FROM public.events newer
          WHERE (newer.supersedes_event_id = e.id))));

-- migrate:down

DROP VIEW IF EXISTS public.current_event_records;

CREATE VIEW public.current_event_records AS
 SELECT e.id,
    e.organization_id,
    e.entity_ids,
    e.origin_id,
    e.title,
    e.payload_type,
    e.payload_text,
    e.payload_data,
    e.payload_template,
    e.attachments,
    e.metadata,
    e.score,
    emb.embedding,
    e.author_name,
    e.source_url,
    e.occurred_at,
    e.created_at,
    e.origin_parent_id,
    COALESCE(length(e.payload_text), 0) AS content_length,
    e.search_tsv,
    e.origin_type,
    e.connector_key,
    e.connection_id,
    e.feed_key,
    e.feed_id,
    e.run_id,
    e.semantic_type,
    e.client_id,
    e.created_by,
    e.interaction_type,
    e.interaction_status,
    e.interaction_input_schema,
    e.interaction_input,
    e.interaction_output,
    e.interaction_error,
    e.supersedes_event_id,
    emb.embedding_model
   FROM (public.events e
     LEFT JOIN public.event_embeddings emb
       ON ((emb.event_id = e.id) AND (emb.chunk_index = 0)))
  WHERE (NOT (EXISTS ( SELECT 1
           FROM public.events newer
          WHERE (newer.supersedes_event_id = e.id))));

-- Lossy dev-only rollback: collapse to one row per event before PK(event_id).
DELETE FROM public.event_embeddings WHERE chunk_index <> 0;
DELETE FROM public.event_embeddings a
  USING public.event_embeddings b
  WHERE a.event_id = b.event_id AND a.ctid < b.ctid;

ALTER TABLE public.event_embeddings DROP CONSTRAINT event_embeddings_pkey;

ALTER TABLE public.event_embeddings
    ADD CONSTRAINT event_embeddings_pkey PRIMARY KEY (event_id);

CREATE UNIQUE INDEX IF NOT EXISTS event_embeddings_event_model_chunk_uniq
    ON public.event_embeddings (event_id, embedding_model, chunk_index);

ALTER TABLE public.event_embeddings ALTER COLUMN embedding_model DROP NOT NULL;