-- migrate:up

-- Durable merge ledger. Entity redirects remain on `entities`; the JSON ledger
-- records the reversible business state changed by one loser→winner operation
-- so Undo can fail closed if later edits made an exact reversal unsafe.
CREATE TABLE IF NOT EXISTS public.entity_merge_operations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id text NOT NULL REFERENCES public.organization(id) ON DELETE CASCADE,
  winner_entity_id bigint NOT NULL REFERENCES public.entities(id),
  loser_entity_id bigint NOT NULL REFERENCES public.entities(id),
  source_run_id bigint REFERENCES public.runs(id) ON DELETE SET NULL,
  watcher_id integer REFERENCES public.watchers(id) ON DELETE SET NULL,
  window_id bigint,
  decision text NOT NULL CHECK (decision IN ('auto_merge', 'human')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'undone')),
  policy_hash text,
  evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  ledger jsonb NOT NULL,
  merged_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  undone_at timestamptz,
  undone_by text
);

CREATE UNIQUE INDEX IF NOT EXISTS entity_merge_operations_one_active_loser
  ON public.entity_merge_operations (organization_id, loser_entity_id)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS entity_merge_operations_winner_created
  ON public.entity_merge_operations (organization_id, winner_entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS entity_merge_operations_source_run
  ON public.entity_merge_operations (source_run_id)
  WHERE source_run_id IS NOT NULL;

-- migrate:down

DROP TABLE IF EXISTS public.entity_merge_operations;
