import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createLogger, type ModelsDevSnapshot } from "@lobu/core";

const logger = createLogger("models-dev-snapshot");

/**
 * Loader for the build-time models.dev snapshot (`config/models-dev-snapshot.json`,
 * generated by `scripts/gen-models-dev-snapshot.ts`).
 *
 * BUILD-TIME ONLY — nothing here fetches models.dev at runtime. The artifact
 * enriches curated picker entries with model details and ships next to
 * `providers.json` in the CLI bundle and app image.
 *
 * Read ONCE and memoized: the file is ~230KB of static build output, and
 * `buildProviderCatalog` runs per catalog request. The cache is per-process
 * derived state re-read identically by every replica from the bundled file —
 * not shared mutable state, so it is multi-replica safe.
 */

/** Resolution order mirrors the bundled defaults in resolveProviderRegistryPath. */
function resolveModelsDevSnapshotPath(): string | undefined {
  const cwdPath = path.resolve(process.cwd(), "config/models-dev-snapshot.json");
  if (existsSync(cwdPath)) return cwdPath;

  const bundleDir = path.dirname(fileURLToPath(import.meta.url));
  const bundleSibling = path.join(bundleDir, "models-dev-snapshot.json");
  if (existsSync(bundleSibling)) return bundleSibling;

  return undefined;
}

let cached: ModelsDevSnapshot | null | undefined;

/**
 * Load the snapshot, or null when it is absent/unreadable/malformed.
 *
 * A missing snapshot DEGRADES, it does not throw: the catalog still lists every
 * provider with its auth metadata, base URL, and curated model IDs; only the
 * optional model details are absent.
 */
function loadModelsDevSnapshot(): ModelsDevSnapshot | null {
  if (cached !== undefined) return cached;

  const snapshotPath = resolveModelsDevSnapshotPath();
  if (!snapshotPath) {
    logger.warn(
      "No models.dev snapshot found (run from a dir with config/models-dev-snapshot.json or use a bundle that ships it) — model details will be unavailable"
    );
    cached = null;
    return cached;
  }

  try {
    const parsed = JSON.parse(
      readFileSync(snapshotPath, "utf-8")
    ) as ModelsDevSnapshot;
    if (!parsed || typeof parsed.providers !== "object") {
      logger.error(
        { snapshotPath },
        "models.dev snapshot missing its `providers` map — ignoring"
      );
      cached = null;
      return cached;
    }
    cached = parsed;
    logger.info(
      {
        providers: Object.keys(parsed.providers).length,
        generatedAt: parsed.generatedAt,
      },
      "Loaded models.dev snapshot"
    );
    return cached;
  } catch (err) {
    logger.error(
      {
        snapshotPath,
        err: err instanceof Error ? err.message : String(err),
      },
      "Failed to read models.dev snapshot — model details will be unavailable"
    );
    cached = null;
    return cached;
  }
}

/**
 * Models for one LOBU provider id (NOT a models.dev id — the snapshot is keyed
 * by Lobu id so callers look up with the id they already hold). Empty when the
 * provider declares no `modelsDevId` or the snapshot is unavailable.
 */
export function getSnapshotModels(providerId: string) {
  return loadModelsDevSnapshot()?.providers[providerId] ?? [];
}
